language: python
os:
  - linux
sudo: false
python:
  - "2.7"
  - "3.6"
script:
  - python setup.py test

install:
  - pip install coveralls

after_success:
  - coveralls
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install typing
  - pip install python-semantic-release
  - semantic-release --minor publish

jobs:
  include:
    - stage: deploy docs
      language: python
      install:
        - pip install mkdocs==1
        - pip install mkdocs-material==3.0.3
      script:
        - mkdir docs/styles
        - mkdir docs/images
        - curl https://api.github.com/repos/compbiocore/cbc-documentation-templates/contents/files/dark_mode.css\?access_token\=$GITHUB_TOKEN > dark_mode.json
        - jq -r '.content' < dark_mode.json | base64 --decode > docs/styles/dark_mode.css
        - curl https://api.github.com/repos/compbiocore/cbc-documentation-templates/contents/files/cbc-logo.svg\?access_token\=$GITHUB_TOKEN > logo.json
        - jq -r '.content' < logo.json | base64 --decode > docs/images/cbc-logo.svg
        - mkdocs build --verbose --clean --strict
      deploy:
       provider: pages
       skip_cleanup: true
       github_token: $GH_TOKEN
       local_dir: site
       on:
         branch: master
