language: python
os:
  - linux
dist: trusty
sudo: false
python:
  - "2.7"
  - "3.4"
script:
  - python setup.py test

jobs:
  include:
    - stage: deploy docs
      os: linux
      language: python
      python:
        - "3.4"
      install:
        - pip install mkdocs==1
        - pip install mkdocs-material==3.0.3
      script:
        - mkdir docs/styles
        - mkdir docs/images
        - curl https://gist.githubusercontent.com/fernandogelin/08ecff3387dffc374c4abf06a577ab71/raw/083a383e51533feb20f3b03e6edcd9e86ddc59f9/dark_mode.css > docs/styles/dark_mode.css
        - curl https://gist.githubusercontent.com/fernandogelin/b02ee98f2f35ce4263093f7a1c66582b/raw/20ca5a37eb6defe00d35e50e7e00a784b64309f9/cbc-logo.svg > docs/images/cbc-logo.svg
        - mkdocs build --verbose --clean --strict
      deploy:
       provider: pages
       skip_cleanup: true
       github_token: $GITHUB_TOKEN
       local_dir: site
       on:
         branch: master
